### ISSUE TITLE
Support single names in footer

### ISSUE THREAD

**Issue by Peterburnett** [catalyst/moodle-tool_emailtemplate#9]
This is for users who only have 1 name eg 'Madonna', 'Zendaya'

This isnt well supported in the core of moodle/totara, but we should work around it here where we can. Probably just a user preference for 'firstname only' or something similar in the footer, which adds a little bit of customisation for this case, or people who want to go by a firstname only in professional communications

**Comment by brendanheywood** [comment]
Is this even a real bug in this plugin? The plugin makes no constraints at all around what user data or fields it uses, the footer mustache template doesn't even need to use any of the fields. I'm not sure what the action is here?

**Comment by brendanheywood** [comment]
Closing this, even if moodle or totara don't support it this can still be worked around in the mustache template
